### ISSUE TITLE
Parry improvements

### ISSUE THREAD

**Issue by MangoLassie142** [Team-Abode/guarding#12]
Hiya,

Just a couple of small suggestions to make the parry a little bit more rewarding without going overboard.

1. If you have Thorns on your shield, a parry should guarantee Thorns damage instead of using the standard chance.
2. A parry should have a chance not to do any durability damage to your shield (like unbreaking). Generally in games with parrying, a parry takes less stamina than a block, so this is a way to immitate that.
3. As well as knockback, I think a parry should do a short stun so that an enemy cannot hit you immediately after the parry if you're moving towards them, giving you a chance to hit first. This could alternatively be a new enchantmet instead - in my opinion even replacing the increased knockback enchant because honestly there comes a point where you're knocking them back so far that you can't even follow up with a hit, which does more harm than good. I think a stun would be more useful than increased knockback.

Love the mod so far <3

**Comment by ExDrill** [comment]
Thank you for your suggestions, I will be considering them for the future.

Additionally, the first suggestion is already a feature in the mod.
