### ISSUE TITLE
IllegalArgumentException: No model for layer guarding:netherite_shield#main

### ISSUE THREAD

**Issue by tigermozze** [Team-Abode/guarding#17]
Hi, I have encountered an issue where this mod crashes the game when im loading into my world. 

**Log: https://mclo.gs/PTns8z4**  (jump to line 23284)

**Comment by ExDrill** [comment]
I've come across this issue multiple times and have marked it as an incompatibility issue, but never which mod specifically. Recently, I've figured out it's the FOG mod which is causing the issue, I'll look into resolving this.

**Comment by Steveplays28** [comment]
Hi @ExDrill, I've fixed this issue in Fog [`v1.4.1`](https://github.com/IMB11/Fog/releases/latest).

**Comment by ExDrill** [comment]
Awesome, looking forward to being able to use FOG again!

**Comment by ExDrill** [comment]
Awesome, looking forward to being able to use FOG again!
