### ISSUE TITLE
Missing Sketch dependency in fabric.mod.json

### ISSUE THREAD

**Issue by Poopooracoocoo** [Team-Abode/guarding#18]
The [Modrinth releases](https://modrinth.com/mod/guarding/version/1.21.1-2.7.3) have the [Sketch](https://modrinth.com/mod/sketch) dependency but since it isn't in the [fabric.mod.json](https://github.com/Team-Abode/guarding/blob/1.21.x/src/main/resources/fabric.mod.json#L33), some users may miss it - especially if they're using Minecraft Launcher where they have to download it from the Modrinth website. Adding the dependency to the FMJ prevents crashes and prompts users to install it.

**Comment by ExDrill** [comment]
Good idea, I'll add this soon to help users!
