### ISSUE TITLE
Banners on netherite shield

### ISSUE THREAD

**Issue by Cuteistfox** [Team-Abode/guarding#2]

**Comment by ExDrill** [comment]
This would take away from the normal shield. However, I may look into adding a feature that refunds the banner from the shield when upgrading.

**Comment by Cuteistfox** [comment]
ill fork it once i learn java and quilt to add baners on shield

**Comment by Cuteistfox** [comment]
refunding banner is important for those using the "thing" banner pattern (from notch apples)
