### ISSUE TITLE
Modded trim materials incompatable with Netherite Shields

### ISSUE THREAD

**Issue by FrogBirdd** [Team-Abode/guarding#3]
Adding trims to shields with modded materials creates a shield with a broken texture

![2024-01-03_20 35 44](https://github.com/Team-Abode/guarding/assets/47127120/18740212-03d9-4d75-a5d5-c8813f947272)

Examples tested are from [https://modrinth.com/mod/pigsteel-fabric](url) and [https://modrinth.com/mod/galosphere-trimming](url)

**Comment by ExDrill** [comment]
You should contact the owner of these packs if they're willing to have compatibility, otherwise you can make a resource pack that gives compatibility.
