### ISSUE TITLE
Shield effectiveness

### ISSUE THREAD

**Issue by duarm** [Team-Abode/guarding#8]
Thanks for making Guarding!

### Problem
Every shield is the same, apart from any additional attribute which does not involve blocking (they grant different armor values, and sometimes knockback resistance).

### Solution
My idea is for each shield to block a different amount of damage via an attribute (so it can be easily modded into other shields). Can guarding do this? or perhaps another mod?

**Comment by ExDrill** [comment]
Was considering something like this originally, but imo it strays a bit too far from the scope of the mod, there are other mods which accomplish a similar functionality, though.
